make install-git
make configure-git
make install-chrome
make install-poetry
make install-pyenv
make install-python
make install-telegram
make install-discord
make install-signal
make install-zoom
make install-obsidian
make install-typora
make install-gimp
make install-obs
make install-vscode
make install-pycharm
make install-docker
